### ISSUE TITLE
erroneous plazi http uris 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/ggxml2taxpub-treatments#24]
the http uri in this taxpub treament for the TB treatment is wrong
https://github.com/plazi/ggxml2taxpub-treatments/blob/main/level1/0384433845052F6CFE68FD53FDA7FD8D_tp_l1.xml

`<tp:treatment-meta>

      <mixed-citation>

         <named-content content-type="treatment-title">Campoplex unicingulatus Schmiedeknecht</named-content>

         <uri content-type="zenodo-doi">http://doi.org/10.5281/zenodo.4638125</uri>

         <uri content-type="treatment-bank-uri">**http://treatment.plazi.org/id/79749C4A8919960B89502BD3F6452ACE**</uri>

         <article-title>Taxonomic revision of the Campoplex difformis group (Ichneumonidae, Campopleginae), with particular reference to species of economic importance</article-title>

         <uri content-type="publication-doi">http://dx.doi.org/10.5852/ejt.2021.740.1277</uri>

      </mixed-citation>`

https://treatment.plazi.org/id/79749C4A8919960B89502BD3F6452ACE
![image](https://user-images.githubusercontent.com/4609956/151444744-08435953-bd23-49c0-9a62-ea800382cecb.png)

and should be http://treatment.plazi.org/id/0384433845052F6CFE68FD53FDA7FD8D

-----------------------

is also in the following XML
https://github.com/plazi/ggxml2taxpub-treatments/blob/main/level1/0384433845092F64FDBFF9E3FE79FE66_tp_l1.xml

http://treatment.plazi.org/id/E3BC919ECF0F6941025E8F594A859411

and should be http://treatment.plazi.org/id/0384433845092F64FDBFF9E3FE79FE66

**Comment by tcatapano** [comment]
Fixed by pulling UUID from treatment element id, not root document element. Closing.

**Comment by gsautter** [comment]
The safest way is using the `docId` attribute from the `document` root element, not the generic `id`.

**Comment by tcatapano** [comment]
implemented. closing
